using DWIS.API.DTO;
using DWIS.Vocabulary.Schemas;
using OSDC.DotnetLibraries.Drilling.DrillingProperties;
using OSDC.UnitConversion.Conversion;
using OSDC.UnitConversion.Conversion.DrillingEngineering;
using System.Reflection;
using DWIS.RigOS.Common.Worker;

namespace DWIS.DAQBridge.CleanSight.Server
{
    public class CleanSightInputData : DWISData
    {
        private static readonly Lazy<IReadOnlyDictionary<string, PropertyInfo>> LocalTopicPropertyMap = new(BuildTopicPropertyMap(typeof(CleanSightInputData)));
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> LocalSparQLQueries = new(BuildSparQLQueries(typeof(CleanSightInputData)));
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> LocalManifests = new(BuildManifests(typeof(CleanSightInputData), "CleanSightInputDataManifest", "DrillDocs", "DWISBridge"));
        public override Lazy<IReadOnlyDictionary<string, PropertyInfo>> TopicPropertyMap { get => LocalTopicPropertyMap; }
        public override Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> SparQLQueries { get => LocalSparQLQueries; }
        public override Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> Manifests { get => LocalManifests; }


        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("BOS_depth")]
        [SemanticFact("BOS_depth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BOS_depth#01", Nouns.Enum.Measurement)]
        [SemanticFact("BOS_depth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.HasDynamicValue, "BOS_depth")]
        [SemanticFact("BOS_depth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [OptionalFact(1, "movingAverageBOS_depth", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "BOS_depth#01", Verbs.Enum.IsTransformationOutput, "movingAverageBOS_depth")]
        [OptionalFact(1, "curvilinearAbscissaFrame#01", Nouns.Enum.OneDimensionalCurviLinearReferenceFrame)]
        [OptionalFact(1, "BOS_depth#01", Verbs.Enum.HasReferenceFrame, "curvilinearAbscissaFrame#01")]
        [OptionalFact(1, "bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [OptionalFact(1, "BOS_depth#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        [OptionalFact(2, "BOS_depth#01", Nouns.Enum.BitDepth)]
        [MQTTTopic("DWIS/Measurement/DepthDrilling/BottomOfStringReferenceLocation/BottomOfStringDepth")]
        public ScalarProperty? BottomOfStringDepth { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("BH_depth")]
        [SemanticFact("BH_depth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BH_depth#01", Nouns.Enum.Measurement)]
        [SemanticFact("BH_depth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BH_depth#01", Verbs.Enum.HasDynamicValue, "BH_depth")]
        [SemanticFact("BH_depth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [OptionalFact(1, "movingAverageBH_depth", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "BH_depth#01", Verbs.Enum.IsTransformationOutput, "movingAverageBH_depth")]
        [OptionalFact(1, "curvilinearAbscissaFrame#01", Nouns.Enum.OneDimensionalCurviLinearReferenceFrame)]
        [OptionalFact(1, "BH_depth#01", Verbs.Enum.HasReferenceFrame, "curvilinearAbscissaFrame#01")]
        [OptionalFact(1, "bh#01", Nouns.Enum.HoleBottomLocation)]
        [OptionalFact(1, "BH_depth#01", Verbs.Enum.IsPhysicallyLocatedAt, "bh#01")]
        [OptionalFact(2, "BH_depth#01", Nouns.Enum.HoleDepth)]
        [MQTTTopic("DWIS/Measurement/DepthDrilling/HoleBottomLocation/BottomHoleDepth")]
        public ScalarProperty? BottomHoleDepth { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("Q_tos")]
        [SemanticFact("Q_tos", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("Q_tos#01", Nouns.Enum.Measurement)]
        [SemanticFact("Q_tos#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("Q_tos#01", Verbs.Enum.HasDynamicValue, "Q_tos")]
        [SemanticFact("Q_tos#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumetricFlowrateDrilling)]
        [OptionalFact(1, "movingAverageQ_tos", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "Q_tos#01", Verbs.Enum.IsTransformationOutput, "movingAverageQ_tos")]
        [OptionalFact(1, "topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [OptionalFact(1, "inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [OptionalFact(1, "topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [OptionalFact(1, "Q_tos#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [OptionalFact(2, "Q_tos#01", Nouns.Enum.FlowRateIn)]
        [MQTTTopic("DWIS/Measurement/VolumetricFlowrateDrilling/TOSInletHydraulicBranch/FlowrateIn")]
        public ScalarProperty? FlowrateIn { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("flowRateOut")]
        [SemanticFact("flowRateOut", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("flowRateOut#01", Nouns.Enum.Measurement)]
        [SemanticFact("flowRateOut#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("flowRateOut#01", Verbs.Enum.HasDynamicValue, "flowRateOut")]
        [SemanticFact("flowRateOut#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumetricFlowrateDrilling)]
        [OptionalFact(1, "movingAverageFlowRateOut", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "flowRateOut#01", Verbs.Enum.IsTransformationOutput, "movingAverageFlowRateOut")]
        [OptionalFact(1, "annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [OptionalFact(1, "outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [OptionalFact(1, "annulusOutletJunction#01", Verbs.Enum.HasDownstreamBranch, "outletHydraulicBranch#01")]
        [OptionalFact(1, "flowRateOut#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [OptionalFact(2, "flowRateOut#01", Nouns.Enum.FlowRateOut)]
        [MQTTTopic("DWIS/Measurement/VolumetricFlowrateDrilling/AnnulusOutletHydraulicBranch/FlowrateOut")]
        public ScalarProperty? FlowrateOut { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("flowRateOutProportion")]
        [SemanticFact("flowRateOutProportion", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("flowRateOutProportion#01", Nouns.Enum.Measurement)]
        [SemanticFact("flowRateOutProportion#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.HasDynamicValue, "flowRateOutProportion")]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.ProportionStandard)]
        [SemanticFact("movingAverageFlowRateOutProportion", Nouns.Enum.MovingAverage)]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.IsTransformationOutput, "movingAverageFlowRateOutProportion")]
        [SemanticFact("annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [SemanticFact("outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("annulusOutletJunction#01", Verbs.Enum.HasDownstreamBranch, "outletHydraulicBranch#01")]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [MQTTTopic("DWIS/Measurement/ProportionStandard/AnnulusOutletHydraulicBranch/FlowrateOutProportion")]
        public ScalarProperty? FlowrateOutProportion { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("blockPosition")]
        [SemanticFact("blockPosition", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("blockPosition#01", Nouns.Enum.Measurement)]
        [SemanticFact("blockPosition#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("blockPosition#01", Verbs.Enum.HasDynamicValue, "blockPosition")]
        [SemanticFact("blockPosition#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.HeightDrilling)]
        [OptionalFact(1, "movingAverageBlockPosition", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "blockPosition#01", Verbs.Enum.IsTransformationOutput, "movingAverageBlockPosition")]
        [OptionalFact(1, "elevator#01", Nouns.Enum.DrillPipeElevator)]
        [OptionalFact(1, "blockPosition#01", Verbs.Enum.IsPhysicallyLocatedAt, "elevator#01")]
        [OptionalFact(2, "blockPosition#01", Nouns.Enum.HookPosition)]
        [MQTTTopic("DWIS/Measurement/HeightDrilling/DrillPipeElevator/BlockPosition")]
        public ScalarProperty? BlockPosition { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("densityIn")]
        [SemanticFact("densityIn", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("densityIn#01", Nouns.Enum.Measurement)]
        [SemanticFact("densityIn#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("densityIn#01", Verbs.Enum.HasDynamicValue, "densityIn")]
        [SemanticFact("densityIn#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [OptionalFact(1, "movingAverageDensityIn", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "densityIn#01", Verbs.Enum.IsTransformationOutput, "movingAverageDensityIn")]
        [OptionalFact(1, "topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [OptionalFact(1, "inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [OptionalFact(1, "topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [OptionalFact(1, "densityIn#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [OptionalFact(2, "densityIn#01", Nouns.Enum.DensityIn)]
        [MQTTTopic("DWIS/Measurement/MassDensityDrilling/TOSInletHydraulicBranch/DrillingFluidDensityIn")]
        public ScalarProperty? DrillingFluidDensityIn { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("densityOut")]
        [SemanticFact("densityOut", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("densityOut#01", Nouns.Enum.Measurement)]
        [SemanticFact("densityOut#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("densityOut#01", Verbs.Enum.HasDynamicValue, "densityOut")]
        [SemanticFact("densityOut#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [OptionalFact(1, "movingAverageDensityOut", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "densityOut#01", Verbs.Enum.IsTransformationOutput, "movingAverageDensityOut")]
        [OptionalFact(1, "returnFlowLine#01", Nouns.Enum.ReturnFlowLine)]
        [OptionalFact(1, "densityOut#01", Verbs.Enum.IsPhysicallyLocatedAt, "returnFlowLine#01")]
        [OptionalFact(1, "annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [OptionalFact(1, "outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [OptionalFact(1, "annulusOutletJunction#01", Verbs.Enum.HasDownstreamBranch, "outletHydraulicBranch#01")]
        [OptionalFact(1, "densityOut#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [OptionalFact(2, "densityOut#01", Nouns.Enum.DensityOut)]
        [MQTTTopic("DWIS/Measurement/MassDensityDrilling/AnnulusOutletHydraulicBranch/DrillingFluidDensityOut")]
        public ScalarProperty? DrillingFluidDensityOut { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("downholeECD")]
        [SemanticFact("downholeECD", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("downholeECD#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholeECD#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholeECD#01", Verbs.Enum.HasDynamicValue, "downholeECD")]
        [SemanticFact("downholeECD#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [OptionalFact(1, "downholePressure#01", Nouns.Enum.Measurement)]
        [OptionalFact(1, "downholePressure#01", Nouns.Enum.ContinuousDataType)]
        [OptionalFact(1, "downholePressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [OptionalFact(1, "movingAverageDownholeECD", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "downholePressure#01", Verbs.Enum.IsTransformationOutput, "movingAverageDownholeECD")]
        [OptionalFact(1, "pressureToDownholeECD", Nouns.Enum.PressureToEquivalentDensityTransformation)]
        [OptionalFact(1, "downholePressure#01", Verbs.Enum.IsTransformationInput, "pressureToDownholeECD")]
        [OptionalFact(1, "downholeECD#01", Verbs.Enum.IsTransformationOutput, "pressureToDownholeECD")]
        [OptionalFact(1, "downholeNetwork", Nouns.Enum.DownholeHydraulicNetwork)]
        [OptionalFact(1, "bhaAnnulus", Nouns.Enum.BHAAnnular)]
        [OptionalFact(1, "downholeNetwork", Verbs.Enum.HasBranchComponent, "bhaAnnulus")]
        [OptionalFact(1, "downholeECD#01", Verbs.Enum.IsEquivalentCirculationDensityAt, "bhaAnnulus")]
        [OptionalFact(1, "downholePressure#01", Verbs.Enum.IsPressureAt, "bhaAnnulus")]
        [OptionalFact(1, "circulating", Nouns.Enum.HydraulicCirculationCondition)]
        [OptionalFact(1, "circulating", Verbs.Enum.IsHydraulicConditionFor, "bhaAnnulus")]
        [OptionalFact(2, "downholeECD#01", Nouns.Enum.DownholeECD)]
        [MQTTTopic("DWIS/Measurement/MassDensityDrilling/BHAAnnulusBranch/DownholeEquivalentCirculationDensity")]
        public ScalarProperty? DownholeEquivalentCirculationDensity { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("downholeESD")]
        [SemanticFact("downholeESD", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("downholeESD#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholeESD#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholeESD#01", Verbs.Enum.HasDynamicValue, "downholeESD")]
        [SemanticFact("downholeESD#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [SemanticFact("downholePressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholePressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("movingAverageDownholeESD", Nouns.Enum.MovingAverage)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsTransformationOutput, "movingAverageDownholeESD")]
        [SemanticFact("pressureToDownholeESD", Nouns.Enum.PressureToEquivalentDensityTransformation)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsTransformationInput, "pressureToDownholeESD")]
        [SemanticFact("downholeESD#01", Verbs.Enum.IsTransformationOutput, "pressureToDownholeESD")]
        [SemanticFact("downholeNetwork", Nouns.Enum.DownholeHydraulicNetwork)]
        [SemanticFact("bhaAnnulus", Nouns.Enum.BHAAnnular)]
        [SemanticFact("downholeNetwork", Verbs.Enum.HasBranchComponent, "bhaAnnulus")]
        [SemanticFact("downholeESD#01", Verbs.Enum.IsEquivalentCirculationDensityAt, "bhaAnnulus")]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsPressureAt, "bhaAnnulus")]
        [SemanticFact("static", Nouns.Enum.HydraulicStaticCondition)]
        [SemanticFact("static", Verbs.Enum.IsHydraulicConditionFor, "bhaAnnulus")]
        [MQTTTopic("DWIS/Measurement/MassDensityDrilling/BHAAnnulusBranch/DownholeEquivalentStaticDensity")]
        public ScalarProperty? DownholeEquivalentStaticDensity { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("activeVolume")]
        [SemanticFact("activeVolume", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("activeVolume#01", Nouns.Enum.Measurement)]
        [SemanticFact("activeVolume#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("activeVolume#01", Verbs.Enum.HasDynamicValue, "activeVolume")]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumeDrilling)]
        [OptionalFact(1, "movingAverageActiveVolume", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "activeVolume#01", Verbs.Enum.IsTransformationOutput, "movingAverageActiveVolume")]
        [OptionalFact(1, "activeDrillingSystem#01", Nouns.Enum.ActiveDrillingSystem)]
        [OptionalFact(1, "activeVolume#01", Verbs.Enum.IsPhysicallyLocatedAt, "activeDrillingSystem#01")]
        [OptionalFact(2, "activeVolume#01", Nouns.Enum.ActiveVolume)]
        [MQTTTopic("DWIS/Measurement/VolumeDrilling/TOSInletHydraulicBranch/ActivePitVolume")]
        public ScalarProperty? ActivePitVolume { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("SPP")]
        [SemanticFact("SPP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("SPP#01", Nouns.Enum.Measurement)]
        [SemanticFact("SPP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("SPP#01", Verbs.Enum.HasDynamicValue, "SPP")]
        [SemanticFact("SPP#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [OptionalFact(1, "movingAverageSPP", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "SPP#01", Verbs.Enum.IsTransformationOutput, "movingAverageSPP")]
        [OptionalFact(1, "standPipe#01", Nouns.Enum.MudStandpipe)]
        [OptionalFact(1, "SPP#01", Verbs.Enum.IsPhysicallyLocatedAt, "standPipe#01")]
        [OptionalFact(2, "SPP#01", Nouns.Enum.SPP)]
        [MQTTTopic("DWIS/Measurement/PressureDrilling/TOSInletHydraulicBranch/StandPipePressure")]
        public ScalarProperty? StandPipePressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("downholeGammaRay")]
        [SemanticFact("downholeGammaRay", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("downholeGammaRay#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholeGammaRay#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.HasDynamicValue, "downholeGammaRay")]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.GammaRayIndexDrilling)]
        [SemanticFact("movingAverageDownholeGammaRay", Nouns.Enum.MovingAverage)]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.IsTransformationOutput, "movingAverageDownholeGammaRay")]
        [SemanticFact("bhaAnnulus", Nouns.Enum.BHAAnnular)]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.IsPhysicallyLocatedAt, "bhaAnnulus")]
        [MQTTTopic("DWIS/Measurement/GammaRayIndexDrilling/BHAAnnulusBranch/DownholeGammaRay")]
        public ScalarProperty? DownholeGammaRay { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("ROP")]
        [SemanticFact("ROP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("ROP#01", Nouns.Enum.Measurement)]
        [SemanticFact("ROP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("ROP#01", Verbs.Enum.HasDynamicValue, "ROP")]
        [SemanticFact("ROP#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.RateOfPenetrationDrilling)]
        [OptionalFact(1, "movingAverageROP", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "ROP#01", Verbs.Enum.IsTransformationOutput, "movingAverageROP")]
        [OptionalFact(1, "tos#01", Nouns.Enum.TopOfStringReferenceLocation)]
        [OptionalFact(1, "ROP#01", Verbs.Enum.IsPhysicallyLocatedAt, "tos#01")]
        [OptionalFact(1, "bh#01", Nouns.Enum.HoleBottomLocation)]
        [OptionalFact(1, "ROP#01", Verbs.Enum.IsDependentOn, "bh#01")]
        [OptionalFact(2, "ROP#01", Nouns.Enum.ROP)]
        [MQTTTopic("DWIS/Measurement/RateOfPenetrationDrilling/HoleBottomLocation/SurfaceRateOfPenetration")]
        public ScalarProperty? SurfaceRateOfPenetration { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("hookLoad")]
        [SemanticFact("hookLoad", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("hookLoad#01", Nouns.Enum.Measurement)]
        [SemanticFact("hookLoad#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("hookLoad#01", Verbs.Enum.HasDynamicValue, "hookLoad")]
        [SemanticFact("hookLoad#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.HookLoadDrilling)]
        [OptionalFact(1, "movingAverageHookLoad", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "hookLoad#01", Verbs.Enum.IsTransformationOutput, "movingAverageHookLoad")]
        [OptionalFact(1, "hook#01", Nouns.Enum.Hook)]
        [OptionalFact(1, "hookLoad#01", Verbs.Enum.IsPhysicallyLocatedAt, "hook#01")]
        [OptionalFact(2, "hookLoad#01", Nouns.Enum.HookLoad)]
        [MQTTTopic("DWIS/Measurement/HookLoadDrilling/Hook/HookLoad")]
        public ScalarProperty? HookLoad { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("surfaceTorque")]
        [SemanticFact("surfaceTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.Measurement)]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.HasDynamicValue, "surfaceTorque")]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [OptionalFact(1, "movingAverageSurfaceTorque", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "surfaceTorque#01", Verbs.Enum.IsTransformationOutput, "movingAverageSurfaceTorque")]
        [OptionalFact(1, "rotatingDriveSystem", Nouns.Enum.RotatingDriveSystemLocation)]
        [OptionalFact(1, "surfaceTorque#01", Verbs.Enum.IsPhysicallyLocatedAt, "rotatingDriveSystem")]
        [OptionalFact(2, "surfaceTorque#01", Nouns.Enum.SurfaceTorque)]
        [MQTTTopic("DWIS/Measurement/TorqueDrilling/RotatingDriveSystemLocation/RotatingDriveSystemTorque")]
        public ScalarProperty? RotatingDriveSystemTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("surfaceRotationalSpeed")]
        [SemanticFact("surfaceRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.Measurement)]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "surfaceRotationalSpeed")]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [OptionalFact(1, "movingAverageSurfaceRotationalSpeed", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "surfaceRotationalSpeed#01", Verbs.Enum.IsTransformationOutput, "movingAverageSurfaceRotationalSpeed")]
        [OptionalFact(1, "rotatingDriveSystem", Nouns.Enum.RotatingDriveSystemLocation)]
        [OptionalFact(1, "surfaceRotationalSpeed#01", Verbs.Enum.IsPhysicallyLocatedAt, "rotatingDriveSystem")]
        [OptionalFact(2, "surfaceRotationalSpeed#01", Nouns.Enum.SurfaceRPM)]
        [MQTTTopic("DWIS/Measurement/AngularVelocityDrilling/RotatingDriveSystemLocation/RotatingDriveSystemRotationalSpeed")]
        public ScalarProperty? RotatingDriveSystemRotationalSpeed { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("lagDepth")]
        [SemanticFact("lagDepth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("lagDepth#01", Nouns.Enum.ComputedData)]
        [SemanticFact("lagDepth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("lagDepth#01", Verbs.Enum.HasDynamicValue, "lagDepth")]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [SemanticFact("movingAverageLagDepth", Nouns.Enum.MovingAverage)]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsTransformationOutput, "movingAverageLagDepth")]
        [SemanticFact("cuttings", Nouns.Enum.CuttingsComponent)]
        [SemanticFact("lagDepth#01", Verbs.Enum.ConcernsAFluidComponent, "cuttings")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.ReturnFlowLine)]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsDependentOn, "bos#01")]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsDependentOn, "returnFlowLine#01")]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsHydraulicallyLocatedAt, "returnFlowLine#01")]
        [MQTTTopic("DWIS/ComputedData/DepthDrilling/ReturnFlowLine/LagDepth")]
        public ScalarProperty? LagDepth { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("lagTime")]
        [SemanticFact("lagTime", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("lagTime#01", Nouns.Enum.ComputedData)]
        [SemanticFact("lagTime#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("lagTime#01", Verbs.Enum.HasDynamicValue, "lagTime")]
        [SemanticFact("lagTime#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DurationDrilling)]
        [SemanticFact("movingAverageLagTime", Nouns.Enum.MovingAverage)]
        [SemanticFact("lagTime#01", Verbs.Enum.IsTransformationOutput, "movingAverageLagTime")]
        [SemanticFact("cuttings", Nouns.Enum.CuttingsComponent)]
        [SemanticFact("lagTime#01", Verbs.Enum.ConcernsAFluidComponent, "cuttings")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.ReturnFlowLine)]
        [SemanticFact("lagTime#01", Verbs.Enum.IsDependentOn, "bos#01")]
        [SemanticFact("lagTime#01", Verbs.Enum.IsDependentOn, "returnFlowLine#01")]
        [SemanticFact("lagTime#01", Verbs.Enum.IsHydraulicallyLocatedAt, "returnFlowLine#01")]
        [MQTTTopic("DWIS/ComputedData/DurationDrilling/ReturnFlowLine/LagTime")]
        public ScalarProperty? LagTime { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticExclusiveOr(1, 2)]
        [SemanticDiracVariable("WOB")]
        [SemanticFact("WOB", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("WOB#01", Nouns.Enum.Measurement)]
        [SemanticFact("WOB#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("WOB#01", Verbs.Enum.HasDynamicValue, "WOB")]
        [SemanticFact("WOB#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [OptionalFact(1, "movingAverageWOB", Nouns.Enum.MovingAverage)]
        [OptionalFact(1, "WOB#01", Verbs.Enum.IsTransformationOutput, "movingAverageWOB")]
        [OptionalFact(1, "tos#01", Nouns.Enum.TopOfStringReferenceLocation)]
        [OptionalFact(1, "WOB#01", Verbs.Enum.IsPhysicallyLocatedAt, "tos#01")]
        [OptionalFact(1, "bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [OptionalFact(1, "bh#01", Nouns.Enum.HoleBottomLocation)]
        [OptionalFact(1, "WOB#01", Verbs.Enum.IsDependentOn, "bos#01")]
        [OptionalFact(1, "WOB#01", Verbs.Enum.IsDependentOn, "bh#01")]
        [OptionalFact(2, "WOB#01", Nouns.Enum.WOB)]
        [MQTTTopic("DWIS/Measurement/WeightOnBitDrilling/HoleBottomLocation/SurfaceWeightOnBit")]
        public ScalarProperty? SurfaceWeightOnBit { get; set; } = null;

        // Gas
        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("gasProportionFlowOutProportion")]
        [SemanticFact("gasProportionFlowOutProportion", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("gasProportionFlowOutProportion#01", Nouns.Enum.Measurement)]
        [SemanticFact("gasProportionFlowOutProportion#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.HasDynamicValue, "gasProportionFlowOutProportion")]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.ProportionStandard)]
        [SemanticFact("movingAverageGasProportionFlowOutProportion", Nouns.Enum.MovingAverage)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.IsTransformationOutput, "movingAverageGasProportionFlowOutProportion")]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.FlowLine)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.IsPhysicallyLocatedAt, "returnFlowLine#01")]
        [SemanticFact("GasComponent#01", Nouns.Enum.GasComponent)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.ConcernsAFluidComponent, "GasComponent#01")]
        [MQTTTopic("DWIS/Measurement/ProportionStandard/ReturnFlowLine/GasProportionFlowOut")]
        public ScalarProperty? GasProportionFlowOut { get; set; } = null;

        // inclination
        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BOS_Inclination")]
        [SemanticFact("BOS_Inclination", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BOS_Inclination#01", Nouns.Enum.Measurement)]
        [SemanticFact("BOS_Inclination#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.HasDynamicValue, "BOS_Inclination")]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PlaneAngleDrilling)]
        [SemanticFact("verticalDirection#01", Nouns.Enum.VerticalDepthFrame)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsMeasuredFromReferenceFrame, "verticalDirection#01")]
        [SemanticFact("movingAverageBOS_Inclination", Nouns.Enum.MovingAverage)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsTransformationOutput, "movingAveragBOS_Inclinatione")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        [MQTTTopic("DWIS/Measurement/PlaneAngleDrilling/BottomOfStringReferenceLocation/BottomOfStringInclination")]
        public ScalarProperty? BottomOfStringInclination { get; set; } = null;

        // TVD
        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BOS_VerticalDepth")]
        [SemanticFact("BOS_VerticalDepth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BOS_VerticalDepth#01", Nouns.Enum.Measurement)]
        [SemanticFact("BOS_VerticalDepth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.HasDynamicValue, "BOS_VerticalDepth")]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [SemanticFact("movingAverageBOS_VerticalDepth", Nouns.Enum.MovingAverage)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.IsTransformationOutput, "movingAverageBOS_VerticalDepth")]
        [SemanticFact("verticalDirection#01", Nouns.Enum.VerticalDepthFrame)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.HasReferenceFrame, "verticalDirection#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        [MQTTTopic("DWIS/Measurement/DepthDrilling/BottomOfStringReferenceLocation/BottomOfStringVerticalDepth")]
        public ScalarProperty? BottomOfStringVerticalDepth { get; set; } = null;

        // PV
        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("PlasticViscosityInlet")]
        [SemanticFact("PlasticViscosityInlet", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("PlasticViscosityInlet#01", Nouns.Enum.ComputedData)]
        [SemanticFact("PlasticViscosityInlet#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.HasDynamicValue, "PlasticViscosityInlet")]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DynamicViscosityDrilling)]
        [SemanticFact("movingAveragePlasticViscosityInlet", Nouns.Enum.MovingAverage)]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.IsTransformationOutput, "movingAveragePlasticViscosityInlet")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BinghamPlasticFluid#01", Nouns.Enum.BinghamPlastic)]
        [SemanticFact("BinghamPlasticFluid#01", Verbs.Enum.HasPlasticViscosity, "PlasticViscosityInlet#01")]
        [MQTTTopic("DWIS/ComputedData/DynamicViscosityDrilling/TOSInletHydraulicBranch/PlasticViscosityAtInlet")]
        public ScalarProperty? PlasticViscosityAtInlet { get; set; } = null;

        // YP
        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("YieldPointInlet")]
        [SemanticFact("YieldPointInlet", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("YieldPointInlet#01", Nouns.Enum.ComputedData)]
        [SemanticFact("YieldPointInlet#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.HasDynamicValue, "YieldPointInlet")]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.FluidShearStress)]
        [SemanticFact("movingAverageYieldPointInlet", Nouns.Enum.MovingAverage)]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.IsTransformationOutput, "movingAverageYieldPointInlet")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BinghamPlasticFluid#01", Nouns.Enum.BinghamPlastic)]
        [SemanticFact("BinghamPlasticFluid#01", Verbs.Enum.HasYieldPoint, "YieldPointInlet#01")]
        [MQTTTopic("DWIS/ComputedData/FluidShearStress/TOSInletHydraulicBranch/YieldPointAtInlet")]
        public ScalarProperty? YieldPointAtInlet { get; set; } = null;

        // bit diameter
        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BitDiameter")]
        [SemanticFact("BitDiameter", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BitDiameter#01", Nouns.Enum.ProcessData)]
        [SemanticFact("BitDiameter#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.HasDynamicValue, "BitDiameter")]
        [SemanticFact("BitDiameter#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DiameterPipeDrilling)]
        [SemanticFact("movingAverageBitDiameter", Nouns.Enum.MovingAverage)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.IsTransformationOutput, "movingAverageBitDiameter")]
        [SemanticFact("RadialReferenceFrame#01", Nouns.Enum.RadialReferenceFrame)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.HasReferenceFrame, "RadialReferenceFrame#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        [MQTTTopic("DWIS/ProcessData/DiameterPipeDrilling/BottomOfStringReferenceLocation/BitDiameter")]
        public ScalarProperty? BitDiameter { get; set; } = null;


    }
}
