using DWIS.API.DTO;
using DWIS.RigOS.Common.Worker;
using DWIS.Vocabulary.Schemas;
using OSDC.DotnetLibraries.Drilling.DrillingProperties;
using OSDC.UnitConversion.Conversion;
using OSDC.UnitConversion.Conversion.DrillingEngineering;
using System.Reflection;

namespace DWIS.DAQBridge.CleanSight.OPCUASource
{
    internal class CleanSightOperationData : DWISData
    {
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> LocalSparQLQueries = new(BuildSparQLQueries(typeof(CleanSightOperationData)));
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> LocalManifests = new(BuildManifests(typeof(CleanSightOperationData), "CleanSightOperationDataManifest", "DrillDocs", "DWISBridge"));
        public override Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> SparQLQueries { get => LocalSparQLQueries; }
        public override Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> Manifests { get => LocalManifests; }

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BOS_depth")]
        [SemanticFact("BOS_depth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BOS_depth#01", Nouns.Enum.Measurement)]
        [SemanticFact("BOS_depth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.HasDynamicValue, "BOS_depth")]
        [SemanticFact("BOS_depth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [SemanticFact("movingAverageBOS_depth", Nouns.Enum.MovingAverage)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.IsTransformationOutput, "movingAverageBOS_depth")]
        [SemanticFact("curvilinearAbscissaFrame#01", Nouns.Enum.OneDimensionalCurviLinearReferenceFrame)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.HasReferenceFrame, "curvilinearAbscissaFrame#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        [SemanticFact("BOS_depth#01", Nouns.Enum.BitDepth)]
        public ScalarProperty? BottomOfStringDepth { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BH_depth")]
        [SemanticFact("BH_depth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BH_depth#01", Nouns.Enum.Measurement)]
        [SemanticFact("BH_depth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BH_depth#01", Verbs.Enum.HasDynamicValue, "BH_depth")]
        [SemanticFact("BH_depth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [SemanticFact("movingAverageBH_depth", Nouns.Enum.MovingAverage)]
        [SemanticFact("BH_depth#01", Verbs.Enum.IsTransformationOutput, "movingAverageBH_depth")]
        [SemanticFact("curvilinearAbscissaFrame#01", Nouns.Enum.OneDimensionalCurviLinearReferenceFrame)]
        [SemanticFact("BH_depth#01", Verbs.Enum.HasReferenceFrame, "curvilinearAbscissaFrame#01")]
        [SemanticFact("bh#01", Nouns.Enum.HoleBottomLocation)]
        [SemanticFact("BH_depth#01", Verbs.Enum.IsPhysicallyLocatedAt, "bh#01")]
        [SemanticFact("BH_depth#01", Nouns.Enum.HoleDepth)]
        public ScalarProperty? BottomHoleDepth { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("Q_tos")]
        [SemanticFact("Q_tos", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("Q_tos#01", Nouns.Enum.Measurement)]
        [SemanticFact("Q_tos#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("Q_tos#01", Verbs.Enum.HasDynamicValue, "Q_tos")]
        [SemanticFact("Q_tos#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumetricFlowrateDrilling)]
        [SemanticFact("movingAverageQ_tos", Nouns.Enum.MovingAverage)]
        [SemanticFact("Q_tos#01", Verbs.Enum.IsTransformationOutput, "movingAverageQ_tos")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Q_tos#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Q_tos#01", Nouns.Enum.FlowRateIn)]
        public ScalarProperty? FlowrateIn { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("flowRateOut")]
        [SemanticFact("flowRateOut", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("flowRateOut#01", Nouns.Enum.Measurement)]
        [SemanticFact("flowRateOut#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("flowRateOut#01", Verbs.Enum.HasDynamicValue, "flowRateOut")]
        [SemanticFact("flowRateOut#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumetricFlowrateDrilling)]
        [SemanticFact("movingAverageFlowRateOut", Nouns.Enum.MovingAverage)]
        [SemanticFact("flowRateOut#01", Verbs.Enum.IsTransformationOutput, "movingAverageFlowRateOut")]
        [SemanticFact("annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [SemanticFact("outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("annulusOutletJunction#01", Verbs.Enum.HasDownstreamBranch, "outletHydraulicBranch#01")]
        [SemanticFact("flowRateOut#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [SemanticFact("flowRateOut#01", Nouns.Enum.FlowRateOut)]
        public ScalarProperty? FlowrateOut { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("flowRateOutProportion")]
        [SemanticFact("flowRateOutProportion", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("flowRateOutProportion#01", Nouns.Enum.Measurement)]
        [SemanticFact("flowRateOutProportion#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.HasDynamicValue, "flowRateOutProportion")]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.ProportionStandard)]
        [SemanticFact("movingAverageFlowRateOutProportion", Nouns.Enum.MovingAverage)]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.IsTransformationOutput, "movingAverageFlowRateOutProportion")]
        [SemanticFact("annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [SemanticFact("outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("annulusOutletJunction#01", Verbs.Enum.HasDownstreamBranch, "outletHydraulicBranch#01")]
        [SemanticFact("flowRateOutProportion#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        public ScalarProperty? FlowrateOutProportion { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("activeVolume")]
        [SemanticFact("activeVolume", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("activeVolume#01", Nouns.Enum.Measurement)]
        [SemanticFact("activeVolume#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("activeVolume#01", Verbs.Enum.HasDynamicValue, "activeVolume")]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumeDrilling)]
        [SemanticFact("movingAverageactiveVolume", Nouns.Enum.MovingAverage)]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsTransformationOutput, "movingAverageactiveVolume")]
        [SemanticFact("activePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsVolumeAt, "activePitLogical#01")]
        public ScalarProperty? ActiveVolume { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("blockPosition")]
        [SemanticFact("blockPosition", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("blockPosition#01", Nouns.Enum.Measurement)]
        [SemanticFact("blockPosition#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("blockPosition#01", Verbs.Enum.HasDynamicValue, "blockPosition")]
        [SemanticFact("blockPosition#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.HeightDrilling)]
        [SemanticFact("movingAverageBlockPosition", Nouns.Enum.MovingAverage)]
        [SemanticFact("blockPosition#01", Verbs.Enum.IsTransformationOutput, "movingAverageBlockPosition")]
        [SemanticFact("elevator#01", Nouns.Enum.DrillPipeElevator)]
        [SemanticFact("blockPosition#01", Verbs.Enum.IsPhysicallyLocatedAt, "elevator#01")]
        [SemanticFact("blockPosition#01", Nouns.Enum.HookPosition)]
        public ScalarProperty? BlockPosition { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("densityIn")]
        [SemanticFact("densityIn", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("densityIn#01", Nouns.Enum.Measurement)]
        [SemanticFact("densityIn#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("densityIn#01", Verbs.Enum.HasDynamicValue, "densityIn")]
        [SemanticFact("densityIn#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [SemanticFact("movingAverageDensityIn", Nouns.Enum.MovingAverage)]
        [SemanticFact("densityIn#01", Verbs.Enum.IsTransformationOutput, "movingAverageDensityIn")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("densityIn#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("densityIn#01", Nouns.Enum.DensityIn)]
        public ScalarProperty? DrillingFluidDensityIn { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("densityOut")]
        [SemanticFact("densityOut", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("densityOut#01", Nouns.Enum.Measurement)]
        [SemanticFact("densityOut#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("densityOut#01", Verbs.Enum.HasDynamicValue, "densityOut")]
        [SemanticFact("densityOut#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [SemanticFact("movingAverageDensityOut", Nouns.Enum.MovingAverage)]
        [SemanticFact("densityOut#01", Verbs.Enum.IsTransformationOutput, "movingAverageDensityOut")]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.ReturnFlowLine)]
        [SemanticFact("densityOut#01", Verbs.Enum.IsPhysicallyLocatedAt, "returnFlowLine#01")]
        [SemanticFact("annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [SemanticFact("outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("annulusOutletJunction#01", Verbs.Enum.HasDownstreamBranch, "outletHydraulicBranch#01")]
        [SemanticFact("densityOut#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [SemanticFact("densityOut#01", Nouns.Enum.DensityOut)]
        public ScalarProperty? DrillingFluidDensityOut { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("downholeECD")]
        [SemanticFact("downholeECD", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("downholeECD#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholeECD#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholeECD#01", Verbs.Enum.HasDynamicValue, "downholeECD")]
        [SemanticFact("downholeECD#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [SemanticFact("downholePressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholePressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("movingAverageDownholeECD", Nouns.Enum.MovingAverage)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsTransformationOutput, "movingAverageDownholeECD")]
        [SemanticFact("pressureToDownholeECD", Nouns.Enum.PressureToEquivalentDensityTransformation)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsTransformationInput, "pressureToDownholeECD")]
        [SemanticFact("downholeECD#01", Verbs.Enum.IsTransformationOutput, "pressureToDownholeECD")]
        [SemanticFact("downholeNetwork", Nouns.Enum.DownholeHydraulicNetwork)]
        [SemanticFact("bhaAnnulus", Nouns.Enum.BHAAnnular)]
        [SemanticFact("downholeNetwork", Verbs.Enum.HasBranchComponent, "bhaAnnulus")]
        [SemanticFact("downholeECD#01", Verbs.Enum.IsEquivalentCirculationDensityAt, "bhaAnnulus")]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsPressureAt, "bhaAnnulus")]
        [SemanticFact("circulating", Nouns.Enum.HydraulicCirculationCondition)]
        [SemanticFact("circulating", Verbs.Enum.IsHydraulicConditionFor, "bhaAnnulus")]
        [SemanticFact("downholeECD#01", Nouns.Enum.DownholeECD)]
        public ScalarProperty? DownholeEquivalentCirculationDensity { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("downholeESD")]
        [SemanticFact("downholeESD", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("downholeESD#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholeESD#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholeESD#01", Verbs.Enum.HasDynamicValue, "downholeESD")]
        [SemanticFact("downholeESD#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [SemanticFact("downholePressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholePressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("movingAverageDownholeESD", Nouns.Enum.MovingAverage)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsTransformationOutput, "movingAverageDownholeESD")]
        [SemanticFact("pressureToDownholeESD", Nouns.Enum.PressureToEquivalentDensityTransformation)]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsTransformationInput, "pressureToDownholeESD")]
        [SemanticFact("downholeESD#01", Verbs.Enum.IsTransformationOutput, "pressureToDownholeESD")]
        [SemanticFact("downholeNetwork", Nouns.Enum.DownholeHydraulicNetwork)]
        [SemanticFact("bhaAnnulus", Nouns.Enum.BHAAnnular)]
        [SemanticFact("downholeNetwork", Verbs.Enum.HasBranchComponent, "bhaAnnulus")]
        [SemanticFact("downholeESD#01", Verbs.Enum.IsEquivalentCirculationDensityAt, "bhaAnnulus")]
        [SemanticFact("downholePressure#01", Verbs.Enum.IsPressureAt, "bhaAnnulus")]
        [SemanticFact("static", Nouns.Enum.HydraulicStaticCondition)]
        [SemanticFact("static", Verbs.Enum.IsHydraulicConditionFor, "bhaAnnulus")]
        public ScalarProperty? DownholeEquivalentStaticDensity { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("activeVolume")]
        [SemanticFact("activeVolume", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("activeVolume#01", Nouns.Enum.Measurement)]
        [SemanticFact("activeVolume#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("activeVolume#01", Verbs.Enum.HasDynamicValue, "activeVolume")]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumeDrilling)]
        [SemanticFact("movingAverageActiveVolume", Nouns.Enum.MovingAverage)]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsTransformationOutput, "movingAverageActiveVolume")]
        [SemanticFact("activeDrillingSystem#01", Nouns.Enum.ActiveDrillingSystem)]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsPhysicallyLocatedAt, "activeDrillingSystem#01")]
        [SemanticFact("activeVolume#01", Nouns.Enum.ActiveVolume)]
        public ScalarProperty? ActivePitVolume { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("SPP")]
        [SemanticFact("SPP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("SPP#01", Nouns.Enum.Measurement)]
        [SemanticFact("SPP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("SPP#01", Verbs.Enum.HasDynamicValue, "SPP")]
        [SemanticFact("SPP#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("movingAverageSPP", Nouns.Enum.MovingAverage)]
        [SemanticFact("SPP#01", Verbs.Enum.IsTransformationOutput, "movingAverageSPP")]
        [SemanticFact("standPipe#01", Nouns.Enum.MudStandpipe)]
        [SemanticFact("SPP#01", Verbs.Enum.IsPhysicallyLocatedAt, "standPipe#01")]
        [SemanticFact("SPP#01", Nouns.Enum.SPP)]
        public ScalarProperty? StandPipePressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("downholeGammaRay")]
        [SemanticFact("downholeGammaRay", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("downholeGammaRay#01", Nouns.Enum.Measurement)]
        [SemanticFact("downholeGammaRay#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.HasDynamicValue, "downholeGammaRay")]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.GammaRayIndexDrilling)]
        [SemanticFact("movingAverageDownholeGammaRay", Nouns.Enum.MovingAverage)]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.IsTransformationOutput, "movingAverageDownholeGammaRay")]
        [SemanticFact("bhaAnnulus", Nouns.Enum.BHAAnnular)]
        [SemanticFact("downholeGammaRay#01", Verbs.Enum.IsPhysicallyLocatedAt, "bhaAnnulus")]
        public ScalarProperty? DownholeGammaRay { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("ROP")]
        [SemanticFact("ROP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("ROP#01", Nouns.Enum.Measurement)]
        [SemanticFact("ROP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("ROP#01", Verbs.Enum.HasDynamicValue, "ROP")]
        [SemanticFact("ROP#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.RateOfPenetrationDrilling)]
        [SemanticFact("movingAverageROP", Nouns.Enum.MovingAverage)]
        [SemanticFact("ROP#01", Verbs.Enum.IsTransformationOutput, "movingAverageROP")]
        [SemanticFact("tos#01", Nouns.Enum.TopOfStringReferenceLocation)]
        [SemanticFact("ROP#01", Verbs.Enum.IsPhysicallyLocatedAt, "tos#01")]
        [SemanticFact("bh#01", Nouns.Enum.HoleBottomLocation)]
        [SemanticFact("ROP#01", Verbs.Enum.IsDependentOn, "bh#01")]
        [SemanticFact("ROP#01", Nouns.Enum.ROP)]
        public ScalarProperty? SurfaceRateOfPenetration { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("hookLoad")]
        [SemanticFact("hookLoad", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("hookLoad#01", Nouns.Enum.Measurement)]
        [SemanticFact("hookLoad#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("hookLoad#01", Verbs.Enum.HasDynamicValue, "hookLoad")]
        [SemanticFact("hookLoad#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.HookLoadDrilling)]
        [SemanticFact("movingAverageHookLoad", Nouns.Enum.MovingAverage)]
        [SemanticFact("hookLoad#01", Verbs.Enum.IsTransformationOutput, "movingAverageHookLoad")]
        [SemanticFact("hook#01", Nouns.Enum.Hook)]
        [SemanticFact("hookLoad#01", Verbs.Enum.IsPhysicallyLocatedAt, "hook#01")]
        [SemanticFact("hookLoad#01", Nouns.Enum.HookLoad)]
        public ScalarProperty? HookLoad { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("surfaceTorque")]
        [SemanticFact("surfaceTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.Measurement)]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.HasDynamicValue, "surfaceTorque")]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("movingAverageSurfaceTorque", Nouns.Enum.MovingAverage)]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.IsTransformationOutput, "movingAverageSurfaceTorque")]
        [SemanticFact("rotatingDriveSystem", Nouns.Enum.RotatingDriveSystemLocation)]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.IsPhysicallyLocatedAt, "rotatingDriveSystem")]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.SurfaceTorque)]
        public ScalarProperty? RotatingDriveSystemTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("surfaceRotationalSpeed")]
        [SemanticFact("surfaceRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.Measurement)]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "surfaceRotationalSpeed")]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [SemanticFact("movingAverageSurfaceRotationalSpeed", Nouns.Enum.MovingAverage)]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.IsTransformationOutput, "movingAverageSurfaceRotationalSpeed")]
        [SemanticFact("rotatingDriveSystem", Nouns.Enum.RotatingDriveSystemLocation)]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.IsPhysicallyLocatedAt, "rotatingDriveSystem")]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.SurfaceRPM)]
        public ScalarProperty? RotatingDriveSystemRotationalSpeed { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("lagDepth")]
        [SemanticFact("lagDepth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("lagDepth#01", Nouns.Enum.ComputedData)]
        [SemanticFact("lagDepth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("lagDepth#01", Verbs.Enum.HasDynamicValue, "lagDepth")]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [SemanticFact("movingAverageLagDepth", Nouns.Enum.MovingAverage)]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsTransformationOutput, "movingAverageLagDepth")]
        [SemanticFact("cuttings", Nouns.Enum.CuttingsComponent)]
        [SemanticFact("lagDepth#01", Verbs.Enum.ConcernsAFluidComponent, "cuttings")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.ReturnFlowLine)]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsDependentOn, "bos#01")]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsDependentOn, "returnFlowLine#01")]
        [SemanticFact("lagDepth#01", Verbs.Enum.IsHydraulicallyLocatedAt, "returnFlowLine#01")]
        public ScalarProperty? LagDepth { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("lagTime")]
        [SemanticFact("lagTime", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("lagTime#01", Nouns.Enum.ComputedData)]
        [SemanticFact("lagTime#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("lagTime#01", Verbs.Enum.HasDynamicValue, "lagTime")]
        [SemanticFact("lagTime#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DurationDrilling)]
        [SemanticFact("movingAverageLagTime", Nouns.Enum.MovingAverage)]
        [SemanticFact("lagTime#01", Verbs.Enum.IsTransformationOutput, "movingAverageLagTime")]
        [SemanticFact("cuttings", Nouns.Enum.CuttingsComponent)]
        [SemanticFact("lagTime#01", Verbs.Enum.ConcernsAFluidComponent, "cuttings")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.ReturnFlowLine)]
        [SemanticFact("lagTime#01", Verbs.Enum.IsDependentOn, "bos#01")]
        [SemanticFact("lagTime#01", Verbs.Enum.IsDependentOn, "returnFlowLine#01")]
        [SemanticFact("lagTime#01", Verbs.Enum.IsHydraulicallyLocatedAt, "returnFlowLine#01")]
        public ScalarProperty? LagTime { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("WOB")]
        [SemanticFact("WOB", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("WOB#01", Nouns.Enum.Measurement)]
        [SemanticFact("WOB#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("WOB#01", Verbs.Enum.HasDynamicValue, "WOB")]
        [SemanticFact("WOB#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("movingAverageWOB", Nouns.Enum.MovingAverage)]
        [SemanticFact("WOB#01", Verbs.Enum.IsTransformationOutput, "movingAverageWOB")]
        [SemanticFact("tos#01", Nouns.Enum.TopOfStringReferenceLocation)]
        [SemanticFact("WOB#01", Verbs.Enum.IsPhysicallyLocatedAt, "tos#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("bh#01", Nouns.Enum.HoleBottomLocation)]
        [SemanticFact("WOB#01", Verbs.Enum.IsDependentOn, "bos#01")]
        [SemanticFact("WOB#01", Verbs.Enum.IsDependentOn, "bh#01")]
        [SemanticFact("WOB#01", Nouns.Enum.WOB)]
        public ScalarProperty? SurfaceWeightOnBit { get; set; } = null;

        // Gas
        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("gasProportionFlowOutProportion")]
        [SemanticFact("gasProportionFlowOutProportion", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("gasProportionFlowOutProportion#01", Nouns.Enum.Measurement)]
        [SemanticFact("gasProportionFlowOutProportion#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.HasDynamicValue, "gasProportionFlowOutProportion")]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.ProportionStandard)]
        [SemanticFact("movingAverageGasProportionFlowOutProportion", Nouns.Enum.MovingAverage)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.IsTransformationOutput, "movingAverageGasProportionFlowOutProportion")]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.FlowLine)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.IsPhysicallyLocatedAt, "returnFlowLine#01")]
        [SemanticFact("GasComponent#01", Nouns.Enum.GasComponent)]
        [SemanticFact("gasProportionFlowOutProportion#01", Verbs.Enum.ConcernsAFluidComponent, "GasComponent#01")]
        public ScalarProperty? GasProportionFlowOut { get; set; } = null;

        // inclination
        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BOS_Inclination")]
        [SemanticFact("BOS_Inclination", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BOS_Inclination#01", Nouns.Enum.Measurement)]
        [SemanticFact("BOS_Inclination#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.HasDynamicValue, "BOS_Inclination")]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PlaneAngleDrilling)]
        [SemanticFact("verticalDirection#01", Nouns.Enum.VerticalDepthFrame)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsMeasuredFromReferenceFrame, "verticalDirection#01")]
        [SemanticFact("movingAverageBOS_Inclination", Nouns.Enum.MovingAverage)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsTransformationOutput, "movingAveragBOS_Inclinatione")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BOS_Inclination#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        public ScalarProperty? BottomOfStringInclination { get; set; } = null;

        // TVD
        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BOS_VerticalDepth")]
        [SemanticFact("BOS_VerticalDepth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BOS_VerticalDepth#01", Nouns.Enum.Measurement)]
        [SemanticFact("BOS_VerticalDepth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.HasDynamicValue, "BOS_VerticalDepth")]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [SemanticFact("movingAverageBOS_VerticalDepth", Nouns.Enum.MovingAverage)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.IsTransformationOutput, "movingAverageBOS_VerticalDepth")]
        [SemanticFact("verticalDirection#01", Nouns.Enum.VerticalDepthFrame)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.HasReferenceFrame, "verticalDirection#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BOS_VerticalDepth#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        public ScalarProperty? BottomOfStringVerticalDepth { get; set; } = null;

        // PV
        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("PlasticViscosityInlet")]
        [SemanticFact("PlasticViscosityInlet", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("PlasticViscosityInlet#01", Nouns.Enum.ComputedData)]
        [SemanticFact("PlasticViscosityInlet#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.HasDynamicValue, "PlasticViscosityInlet")]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DynamicViscosityDrilling)]
        [SemanticFact("movingAveragePlasticViscosityInlet", Nouns.Enum.MovingAverage)]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.IsTransformationOutput, "movingAveragePlasticViscosityInlet")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("PlasticViscosityInlet#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BinghamPlasticFluid#01", Nouns.Enum.BinghamPlastic)]
        [SemanticFact("BinghamPlasticFluid#01", Verbs.Enum.HasPlasticViscosity, "PlasticViscosityInlet#01")]
        public ScalarProperty? PlasticViscosityAtInlet { get; set; } = null;

        // YP
        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("YieldPointInlet")]
        [SemanticFact("YieldPointInlet", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("YieldPointInlet#01", Nouns.Enum.ComputedData)]
        [SemanticFact("YieldPointInlet#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.HasDynamicValue, "YieldPointInlet")]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.FluidShearStress)]
        [SemanticFact("movingAverageYieldPointInlet", Nouns.Enum.MovingAverage)]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.IsTransformationOutput, "movingAverageYieldPointInlet")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("YieldPointInlet#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BinghamPlasticFluid#01", Nouns.Enum.BinghamPlastic)]
        [SemanticFact("BinghamPlasticFluid#01", Verbs.Enum.HasYieldPoint, "YieldPointInlet#01")]
        public ScalarProperty? YieldPointAtInlet { get; set; } = null;

        // bit diameter
        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BitDiameter")]
        [SemanticFact("BitDiameter", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BitDiameter#01", Nouns.Enum.ProcessData)]
        [SemanticFact("BitDiameter#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.HasDynamicValue, "BitDiameter")]
        [SemanticFact("BitDiameter#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DiameterPipeDrilling)]
        [SemanticFact("movingAverageBitDiameter", Nouns.Enum.MovingAverage)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.IsTransformationOutput, "movingAverageBitDiameter")]
        [SemanticFact("RadialReferenceFrame#01", Nouns.Enum.RadialReferenceFrame)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.HasReferenceFrame, "RadialReferenceFrame#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BitDiameter#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        public ScalarProperty? BitDiameter { get; set; } = null;
    }
}
